### ISSUE TITLE
mavplayback.py issue for binary file

### ISSUE THREAD

**Issue by capaulson** [tridge/MAVProxy#143]
When I run:

mavplayback.py 252.BIN

I receive this error:
Traceback (most recent call last):
  File "/usr/local/bin/mavplayback.py", line 4, in <module>
    __import__('pkg_resources').run_script('pymavlink==1.1.53', 'mavplayback.py')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-8.2.1-py2.7.egg/pkg_resources.py", line 646, in run_script
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-8.2.1-py2.7.egg/pkg_resources.py", line 1567, in run_script
  File "/usr/local/lib/python2.7/site-packages/pymavlink-1.1.53-py2.7-macosx-10.10-x86_64.egg/EGG-INFO/scripts/mavplayback.py", line 246, in <module>
    app=App(filename)
  File "/usr/local/lib/python2.7/site-packages/pymavlink-1.1.53-py2.7-macosx-10.10-x86_64.egg/EGG-INFO/scripts/mavplayback.py", line 97, in __init__
    self.next_message()
  File "/usr/local/lib/python2.7/site-packages/pymavlink-1.1.53-py2.7-macosx-10.10-x86_64.egg/EGG-INFO/scripts/mavplayback.py", line 189, in next_message
    pos = float(self.mlog.f.tell()) / self.filesize
AttributeError: 'DFReader_binary' object has no attribute 'f'

The BIN file is off the Arduplane software stack running on a PX4. 

Thanks, Chris

**Comment by AndKe** [comment]
Strange, but now I see the same on one recently computer, 
```
$ mavplayback.py ~/apmplanner2/dataflashLogs/Solo4.0.1.bin 
Traceback (most recent call last):
  File "/home/andre/.local/bin/mavplayback.py", line 256, in <module>
    app=App(filename)
  File "/home/andre/.local/bin/mavplayback.py", line 104, in __init__
    self.next_message()
  File "/home/andre/.local/bin/mavplayback.py", line 199, in next_message
    pos = float(self.mlog.f.tell()) / self.filesize
AttributeError: 'DFReader_binary' object has no attribute 'f'

```
