### ISSUE TITLE
Link remove appears to not be closing the serial port

### ISSUE THREAD

**Issue by gmorph** [tridge/MAVProxy#96]
AUTO> link remove 1
AUTO> Removing link tcp:127.0.0.1:5762

AUTO> link list
AUTO> 1 links
0: tcp:127.0.0.1:5760

In another window I then ran
mavproxy.py --master tcp:127.0.0.1:5762 --out /dev/serial/by-id/usb-FTDI_FT231X_USB_UART_DN008VDD-if00-port0 --baudrate 57600

and got the exception below:

AUTO> Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/grant/.local/lib/python2.7/site-packages/MAVProxy-1.4.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 724, in main_loop
  File "/home/grant/.local/lib/python2.7/site-packages/MAVProxy-1.4.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 507, in process_mavlink
  File "/home/grant/.local/lib/python2.7/site-packages/pymavlink/mavutil.py", line 730, in recv
    ret = self.port.read(n)
  File "/home/grant/.local/lib/python2.7/site-packages/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by amilcarlucas** [comment]
Could you try https://github.com/ArduPilot/pymavlink/pull/212 to see if it fixes it?
